FLAGS= -ansi -Wall -O0 -g3 -lncurses -lm -framework IOKit -framework CoreFoundation -framework OpenGL -framework GLUT -framework ApplicationServices

all: client.cpp
	g++ -o client client.cpp libstem_Gamepad.a $(FLAGS)