#!/usr/bin/perl -w

# standard deviation calculater for stat.txt generated by client

open (my $FILE, "<", "stat.txt") or die "failed to open stat.txt";
my @DATA = <$FILE>;
close ($FILE);

my @item = ($DATA[0] =~ m/(\w+)\s/g);
shift @DATA;

@ARGV = @item unless (@ARGV);

foreach $argv (@ARGV) {
  my ($index) = grep {$item[$_] eq $argv} (0..$#item);
  
  # mean
  my $mean = 0;
  my $n = 0;
  foreach (@DATA) {
    my @value = ($_ =~ m/(\S+)\s/g);
    $mean += $value[$index];
    $n++;
  }
  $mean /= $n;
  
  # std
  my $sd = 0;
  foreach (@DATA) {
    @value = ($_ =~ m/(\S+)\s/g);
    $sd += ($value[$index]-$mean)**2;
  }
  $sd /= $n-1;
  
  print "statistic of $argv:\nsamples: $n\nmean: $mean\nsd^2: $sd\n\n";
}
